#!/bin/bash -l
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --mem=16G
#SBATCH --ntasks-per-node=1
#SBATCH --sockets-per-node=1
#SBATCH --partition=m1,m2,m3
#SBATCH --job-name=mot_simul
#SBATCH --output=JOB.o

N=$1
B_prime=$2
T_init=$3
R_init=$4

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# running
source ./venv/bin/activate
python3 simulation.py $N $B_prime $T_init $R_init

